/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tablero;

import Ficha.Ficha;
import java.awt.Color;

/**
 *
 * @author JoseLuis
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    Ficha tablero[][];
    boolean primero;
    int f1,f2,c1,c2;
    Color colors;
    public Tablero() {
        initComponents();
        f1=-1;f2=-1;c1=-1;c1=-1;
        primero=false;
        colors=Color.WHITE;
        tablero=new Ficha[10][10];
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p01 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p02 = new javax.swing.JButton();
        p11 = new javax.swing.JButton();
        p12 = new javax.swing.JButton();
        p20 = new javax.swing.JButton();
        p21 = new javax.swing.JButton();
        p22 = new javax.swing.JButton();
        p00 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p01.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p01, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 70, 60));

        jButton2.setText("jButton1");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, 60));

        p10.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 70, 60));

        p02.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p02, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 70, 60));

        p11.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 70, 60));

        p12.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 70, 60));

        p20.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 70, 60));

        p21.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 70, 60));

        p22.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 70, 60));

        p00.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(p00, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    void mover(String nombre,Color color,int F,int C){
    
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton p00;
    private javax.swing.JButton p01;
    private javax.swing.JButton p02;
    private javax.swing.JButton p10;
    private javax.swing.JButton p11;
    private javax.swing.JButton p12;
    private javax.swing.JButton p20;
    private javax.swing.JButton p21;
    private javax.swing.JButton p22;
    // End of variables declaration//GEN-END:variables
}
